version: '3'

services:
  api:
    build: ./docker-api
    env_file:
    - ./api-variables.env
    container_name: tap_web
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  db:
    image: mariadb:10.5.9-focal
    container_name: tap_db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: tap
      MYSQL_USER: tap
      MYSQL_PASSWORD: taptap2
    ports:
      - "3306:3306"
    volumes:
      - tap_db:/var/lib/mysql
volumes:
  tap_db:
