version: '3'

services:
  api:
    build: ./docker-api
    env_file:
    - ./api-variables.env
    container_name: web-kata
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true
